tid: "fedreid"
server:
  test_all: False
  clients_per_round: 9
  test_every: 10
  rounds: 300
  batch_size: 32
  aggregation_content: "parameters"
resource_heterogeneous:
  simulate: False
  pre_profile: False
  total_time: 0
  grouping_strategy: "greedy"
client:
  local_epoch: 1
  track: False
  batch_size: 32
  optimizer:
    type: "SGD"
    lr: 0.05
    momentum: 0.9
test_mode: "test_in_client"
test_method: "average"