apiVersion: v1
kind: Service
metadata:
  name: easyfl-server-svc
  namespace: easyfl
spec:
  type: NodePort
  selector:
    app: easyfl-server
  ports:
    - protocol: TCP
      port: 23501
      targetPort: 23501
      nodePort: 32501
---
apiVersion: v1
kind: Service
metadata:
  name: easyfl-client-svc
  namespace: easyfl
spec:
  clusterIP: None
  selector:
    app: easyfl-client
  ports:
    - protocol: TCP
      port: 23400
      targetPort: 23400
---
apiVersion: v1
kind: Service
metadata:
  name: easyfl-tracker-svc
  namespace: easyfl
spec:
  type: NodePort
  selector:
    app: easyfl-tracker
  ports:
    - protocol: TCP
      port: 12666
      targetPort: 12666
      nodePort: 32666
